### ISSUE TITLE
Garrett Johnson to update nameservers

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-northpointe#1]
Waiting on Garrett Johnson to respond and update nameservers for us. 

Once this happens, we'll see the domain show up in our FTP and @AaronAguilar can upload the site. 

This task is WAITING ON EXTERNAL ASSISTANCE

**Comment by rodneystrong** [comment]
Heard back from Garrett; promised to make the change tonight.

**Comment by AaronAguilar** [comment]
Hello,

I uploaded the NorthPointe site folder to the NorthPointeIndia.com <http://northpointeindia.com/> folder. 

Regards,

Aaron

**Comment by AaronAguilar** [comment]
It’s live now.
